# Generated by Django 4.1.5 on 2023-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
